FROM $[DOCKER_REGISTRY]/$[DOCKER_NAME]:ubuntu-$[UBUNTU_VERSION]

LABEL name="$[DOCKER_REGISTRY]/$[DOCKER_NAME]:ubuntu-$[UBUNTU_VERSION]-$[AZDO_AGENT_VERSION]" \
      maintainer="Pmorisseau - CodeZ.one - Kirsten Kluge" \
      version="0.1.0"

# Install AZ CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
RUN echo "AZURE_EXTENSION_DIR=/usr/local/lib/azureExtensionDir" | tee -a /etc/environment \
    && mkdir -p /usr/local/lib/azureExtensionDir

# Install powershell core
RUN wget -q "https://packages.microsoft.com/config/ubuntu/$[UBUNTU_VERSION]/packages-microsoft-prod.deb" \
        && dpkg -i packages-microsoft-prod.deb \
        && apt-get update \
        && apt-get install -y powershell

#Install Kubectl
RUN curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update \
    && apt-get install -y kubectl

#Install Helm
RUN curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
RUN apt-get update \
    && apt-get install helm

COPY ./runAgent.sh /azdo/

RUN chmod +x /azdo/runAgent.sh \
 && set -x \
 && cd /azdo \
 && curl -s -fSL https://vstsagentpackage.azureedge.net/agent/$[AZDO_AGENT_VERSION]/vsts-agent-linux-x64-$[AZDO_AGENT_VERSION].tar.gz -o agent.tgz \
 && mkdir agent \
 && cd agent \
 && tar -xzf ../agent.tgz \
 && chown -R root:root . \
 && cd .. \
 && rm agent.tgz

COPY ./installdependencies.sh /azdo/agent/bin/

RUN chmod +x /azdo/agent/bin/installdependencies.sh

RUN /azdo/agent/bin/installdependencies.sh

CMD ["/azdo/runAgent.sh"]
