FROM $[DOCKER_REGISTRY]/$[DOCKER_NAME]:ubuntu-$[UBUNTU_VERSION]

LABEL name="$[DOCKER_REGISTRY]/$[DOCKER_NAME]:ubuntu-$[UBUNTU_VERSION]-$[AZDO_AGENT_VERSION]" \
      maintainer="Pmorisseau - CodeZ.one - Kirsten Kluge" \
      version="0.1.0"

# Install AZ CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
RUN echo "AZURE_EXTENSION_DIR=/usr/local/lib/azureExtensionDir" | tee -a /etc/environment \
    && mkdir -p /usr/local/lib/azureExtensionDir

# Install powershell core
RUN wget -q "https://packages.microsoft.com/config/ubuntu/$[UBUNTU_VERSION]/packages-microsoft-prod.deb" \
        && dpkg -i packages-microsoft-prod.deb \
        && apt-get update \
        && apt-get install -y powershell

# Install AZ CLI for powershell
RUN pwsh -NoLogo -NoProfile -Command "Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force"

#Install Kubectl
RUN curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /usr/share/keyrings/kubernetes-apt-keyring.gpg
RUN echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update \
    && apt-get install -y kubectl

#Install Helm
RUN curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
RUN apt-get update \
    && apt-get install helm

COPY ./runAgent.sh /azdo/

RUN chmod +x /azdo/runAgent.sh \
 && set -x \
 && cd /azdo \
 && curl -s -fSL https://vstsagentpackage.azureedge.net/agent/$[AZDO_AGENT_VERSION]/vsts-agent-linux-x64-$[AZDO_AGENT_VERSION].tar.gz -o agent.tgz \
 && mkdir agent \
 && cd agent \
 && tar -xzf ../agent.tgz \
 && chown -R root:root . \
 && cd .. \
 && rm agent.tgz

COPY ./installdependencies.sh /azdo/agent/bin/

RUN chmod +x /azdo/agent/bin/installdependencies.sh

RUN /azdo/agent/bin/installdependencies.sh

RUN apt-get install --no-install-recommends \
      unzip \
      libunwind-dev \
      gettext \
      zlib1g \
      libicu-dev \
      && set -x \
      && export DOTNET_CLI_TELEMETRY_OPTOUT=1 \
      && curl -sSL -o dotnet-install.sh https://dot.net/v1/dotnet-install.sh \
      && chmod +x dotnet-install.sh \
      && ./dotnet-install.sh  --channel "LTS" --version "6.0.403" --architecture "x64" --install-dir /opt/dotnet --no-path \
      && ln -s /opt/dotnet/dotnet /usr/local/bin \
      && dotnet help >/dev/null \
      && apt-get clean

ENV dotnet=/usr/bin/dotnet

RUN dotnet tool install -g microsoft.sqlpackage

CMD ["/azdo/runAgent.sh"]
