FROM ubuntu:$[UBUNTU_VERSION]

LABEL name="$[DOCKER_REGISTRY]/$[DOCKER_NAME]:ubuntu-$[UBUNTU_VERSION]" \
      maintainer="Pmorisseau - CodeZ.one - Kirsten Kluge" \
      version="0.1.0"

ARG PROXY=""
ARG NO_PROXY=""

ENV http_proxy=$PROXY
ENV https_proxy=$PROXY
ENV no_proxy=$NO_PROXY

# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update  \
 && apt-get install apt-utils
RUN apt-get install --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    curl \
    file \
    ftp \
    git \
    gnupg \
    gss-ntlmssp \
    iproute2 \
    iputils-ping \
    locales \
    lsb-release \
    sudo \
    time \
    unzip \
    wget \
    zip \
    software-properties-common \
    powershell \
 && rm -rf /var/lib/apt/lists/* \
 && apt-get clean

# Install AZ CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
RUN echo "AZURE_EXTENSION_DIR=/usr/local/lib/azureExtensionDir" | tee -a /etc/environment \
    && mkdir -p /usr/local/lib/azureExtensionDir

# Install powershell core
RUN wget -q "https://packages.microsoft.com/config/ubuntu/$[UBUNTU_VERSION]/packages-microsoft-prod.deb" \
        && dpkg -i packages-microsoft-prod.deb \
        && apt-get update \
        && apt-get install -y powershell

