trigger:
- master

jobs:
- job: Windows
  displayName: 'Build windows images'
  pool:
    vmImage: 'windows-latest'
  workspace:
    clean: all
  variables:
    workingDirectory: '$(Build.SourcesDirectory)/windows/'
  steps:
  - task: PowerShell@2
    targetType: filepath
    filePath: .\build.ps1
    displayName: 'Build images'
    workingDirectory: $(workingDirectory)    

  - task: Docker@2
    displayName: 'Docker Login'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      containerRegistry: 'pmorisseau Docker Hub'
      command: 'login'
      addPipelineData: false
  
  - task: PowerShell@2
    targetType: filepath
    filePath: .\push.ps1
    displayName: 'Push images'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    workingDirectory: $(workingDirectory)
