FROM $[DOCKER_REGISTRY]/$[DOCKER_NAME]:$[AZDO_AGENT_TAG]

LABEL name="$[DOCKER_REGISTRY]/$[DOCKER_NAME]:$[AZDO_AGENT_TAG]-dotnet-$[DOTNET_VERSION]" \
      maintainer="Pmorisseau - CodeZ.one - Kirsten Kluge" \
      version="0.1.0"

WORKDIR /usr

RUN apt-get install --no-install-recommends \
      unzip \
      libunwind-dev \
      gettext \
      zlib1g \
      libicu-dev
      
RUN set -x
RUN export DOTNET_CLI_TELEMETRY_OPTOUT=1
RUN curl -sSL -o dotnet-install.sh https://dot.net/v1/dotnet-install.sh
RUN chmod +x dotnet-install.sh
RUN ./dotnet-install.sh  --channel "LTS" --version "$[DOTNET_SDK_VERSION]" --architecture "x64" --install-dir /opt/dotnet --no-path
RUN ln -s /opt/dotnet/dotnet /usr/local/bin
RUN dotnet help >/dev/null
RUN apt-get clean

ENV dotnet=/usr/bin/dotnet